version: "3.7"
services:
  user.db:
    container_name: user.db
    restart: "no"
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
    networks:
      - user-network

  user.api:
    container_name: user.api
    ports:
      - "8080:8080"
    restart: "no"
    build:
      context: ../
      dockerfile:  Dockerfile
    networks:
      - user-network
    env_file:
      - ../.env
    depends_on:
      - user.db

volumes:
  data: {}

networks:
  user-network:
    driver: bridge
